Update ci-trigger.yml

diff --git a/.github/workflows/ci-trigger.yml b/.github/workflows/ci-trigger.yml
--- a/.github/workflows/ci-trigger.yml
+++ b/.github/workflows/ci-trigger.yml
@@ -101,36 +101,39 @@ jobs:
           echo "::set-output name=matrix::{\"workflow\":[$MATRIX]}"
           echo "::set-output name=runner::$RUNNER"
 
-  trigger-workflow:
-    name: Trigger Workflow
+  call-workflow:
+    uses: lxbndr/gha-experiments/.github/workflows/icu.yml@main
 
-    runs-on: ubuntu-latest
-    needs: [configure]
+#   trigger-workflow:
+#     name: Trigger Workflow
 
-    strategy:
-      fail-fast: false
-      matrix:
-        ${{ fromJSON(needs.configure.outputs.matrix) }}
+#     runs-on: ubuntu-latest
+#     needs: [configure]
 
-    steps:
-      - name: Create Check Run
-        id: create_check
-        run: |
-          set -e
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         ${{ fromJSON(needs.configure.outputs.matrix) }}
+
+#     steps:
+#       - name: Create Check Run
+#         id: create_check
+#         run: |
+#           set -e
           
-          http_code=$(curl -s -o check.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
-            -X POST https://api.github.com/repos/${{ github.repository }}/check-runs \
-            -d '{"name":"${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].check_name }}","head_sha":"${{ needs.configure.outputs.head_sha }}"}')
+#           http_code=$(curl -s -o check.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
+#             -X POST https://api.github.com/repos/${{ github.repository }}/check-runs \
+#             -d '{"name":"${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].check_name }}","head_sha":"${{ needs.configure.outputs.head_sha }}"}')
           
-          if [ "$http_code" != "201" ]; then
-            echo "::error::Failed to create check"
-            exit 1
-          fi
+#           if [ "$http_code" != "201" ]; then
+#             echo "::error::Failed to create check"
+#             exit 1
+#           fi
           
-          CHECK_RUN_ID=$(jq -r '.id' check.json)
+#           CHECK_RUN_ID=$(jq -r '.id' check.json)
           
-          echo "Check run ID: $CHECK_RUN_ID"
-          echo "::set-output name=check_run_id::$CHECK_RUN_ID"
+#           echo "Check run ID: $CHECK_RUN_ID"
+#           echo "::set-output name=check_run_id::$CHECK_RUN_ID"
 
 #       - name: Trigger Workflow
 #         run: |
@@ -144,20 +147,17 @@ jobs:
 #             https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].workflow_id }}/dispatches \
 #             -d '{"ref":"${{ needs.configure.outputs.head_ref }}","inputs":{"check_run_id":"${{ steps.create_check.outputs.check_run_id }}"${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].workflow_inputs }}'"$RUNS_ON"'}}')
       
-      - name: Trigger Workflow
-        uses: .github/workflow/icu.yml@main
-
-      - name: Update Check Run
-        if: failure()
-        run: |
-          set -e
+#       - name: Update Check Run
+#         if: failure()
+#         run: |
+#           set -e
           
-          http_code=$(curl -s -o check.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
-            -X PATCH https://api.github.com/repos/${{ github.repository }}/check-runs/${{ steps.create_check.outputs.check_run_id }} \
-            -d '{"conclusion":"failure"}')
+#           http_code=$(curl -s -o check.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
+#             -X PATCH https://api.github.com/repos/${{ github.repository }}/check-runs/${{ steps.create_check.outputs.check_run_id }} \
+#             -d '{"conclusion":"failure"}')
           
-          echo $http_code
-          if [ "$http_code" != "200" ]; then
-            echo "::error::Failed to update check run"
-            exit 1
-          fi
+#           echo $http_code
+#           if [ "$http_code" != "200" ]; then
+#             echo "::error::Failed to update check run"
+#             exit 1
+#           fi
