Update ci-trigger-2.yml

diff --git a/.github/workflows/ci-trigger-2.yml b/.github/workflows/ci-trigger-2.yml
--- a/.github/workflows/ci-trigger-2.yml
+++ b/.github/workflows/ci-trigger-2.yml
@@ -21,8 +21,59 @@ jobs:
 
       - name: Set Matrix
         id: set-matrix
-        run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
-        
+        env:
+          AUTHOR_ASSOCIATION: ${{ github.event.comment.author_association }}
+          COMMENT_BODY: ${{ github.event.comment.body }}
+        run: |
+          if [ "$AUTHOR_ASSOCIATION" != "COLLABORATOR" ] && [ "$AUTHOR_ASSOCIATION" != "OWNER" ]; then
+            echo "::error::Only collaborators or owner could request this action"
+            exit 1
+          fi
+          
+          case '$COMMENT_BODY' in 
+            *swift-5.3*)
+            echo "Has swift-5.3"
+            ;;
+          esac
+          
+          case '$COMMENT_BODY' in 
+            *swift-5.4*)
+            echo "Has swift-5.4"
+            ;;
+          esac
+          
+          case '$COMMENT_BODY' in 
+            *swift-5.5*)
+            echo "Has swift-5.5"
+            ;;
+          esac
+
+          case '$COMMENT_BODY' in 
+            *curl*)
+            echo "Has curl"
+            ;;
+          esac
+
+          case '$COMMENT_BODY' in 
+            *libxml2*)
+            echo "Has libxml2"
+            ;;
+          esac
+
+          case '$COMMENT_BODY' in 
+            *icu*)
+            echo "Has icu"
+            ;;
+          esac
+          
+          case '$COMMENT_BODY' in 
+            *zlib*)
+            echo "Has zlib"
+            ;;
+          esac
+          
+          echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
+
   trigger-workflows:
     name: Trigger Workflows
 
@@ -111,7 +162,7 @@ jobs:
 #             && echo "::set-output name=check_run_id::$CHECK_RUN_ID"
 
 #       - name: Trigger curl Workflow
-#         if: contains(github.event.comment.body, 'libxml2') || contains(github.event.comment.body, 'all')
+#         if: contains(github.event.comment.body, 'curl') || contains(github.event.comment.body, 'all')
 #         run: |
 #           curl -s -H 'Authorization: token ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}' \
 #             https://api.github.com/repos/${{ github.repository }}/actions/workflows/curl.yml/dispatches \
