Update ci-trigger-2.yml

diff --git a/.github/workflows/ci-trigger-2.yml b/.github/workflows/ci-trigger-2.yml
--- a/.github/workflows/ci-trigger-2.yml
+++ b/.github/workflows/ci-trigger-2.yml
@@ -94,6 +94,11 @@ jobs:
           http_code=$(curl -s -o pr.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
             https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
           
+          if [ $httpCode != 201 ]; then
+            echo "::error::Failed to fetch PR ${{ github.event.issue.number }}"
+            exit 1
+          fi
+          
           HEAD_SHA=$(jq -r '.head.sha' pr.json)
           HEAD_REF=$(jq -r '.head.ref' pr.json)
           
