Update ci-trigger-2.yml

diff --git a/.github/workflows/ci-trigger-2.yml b/.github/workflows/ci-trigger-2.yml
--- a/.github/workflows/ci-trigger-2.yml
+++ b/.github/workflows/ci-trigger-2.yml
@@ -18,21 +18,45 @@ env:
     }
 
 jobs:
-  set-matrix:
-    name: Set Matrix
+  configure:
+    name: Configure Builds
 
     runs-on: ubuntu-latest
     if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/ci ')
 
     outputs:
-      matrix: ${{ steps.set-matrix.outputs.matrix }}
+      matrix: ${{ steps.set_matrix.outputs.matrix }}
+      head_sha: ${{ steps.get_pr.outputs.head_sha }}
+      head_ref: ${{ steps.get_pr.outputs.head_ref }}
 
     steps:
       - name: Print Debug Info
         run: echo "${{ github.event.comment.author_association }}"
 
+      - name: Fetch Pull Request Info
+        id: get_pr
+        run: |
+          set -e
+          
+          http_code=$(curl -s -o pr.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
+            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
+          
+          if [ "$http_code" != "200" ]; then
+            echo "::error::Failed to fetch PR ${{ github.event.issue.number }}"
+            exit 1
+          fi
+          
+          HEAD_SHA=$(jq -r '.head.sha' pr.json)
+          HEAD_REF=$(jq -r '.head.ref' pr.json)
+          
+          echo "Head SHA: $HEAD_SHA"
+          echo "Head ref: $HEAD_REF"
+          
+          echo "::set-output name=head_sha::$HEAD_SHA"
+          echo "::set-output name=head_ref::$HEAD_REF"
+
       - name: Set Matrix
-        id: set-matrix
+        id: set_matrix
         env:
           AUTHOR_ASSOCIATION: ${{ github.event.comment.author_association }}
           COMMENT_BODY: ${{ github.event.comment.body }}
@@ -74,43 +98,24 @@ jobs:
     name: Trigger Workflow
 
     runs-on: ubuntu-latest
-    needs: [set-matrix]
+    needs: [configure]
 
     strategy:
       fail-fast: false
       matrix:
-        ${{ fromJSON(needs.set-matrix.outputs.matrix) }}
+        ${{ fromJSON(needs.configure.outputs.matrix) }}
 
     steps:
       - name: Print Debug Info
         run: |
           echo "${{ toJSON(matrix) }}"
-          
-      - name: Fetch Pull Request Info
-        id: get_pr
-        run: |
-          set -e
-          
-          http_code=$(curl -s -o pr.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
-            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
-          
-          if [ "$http_code" != "200" ]; then
-            echo "::error::Failed to fetch PR ${{ github.event.issue.number }}"
-            exit 1
-          fi
-          
-          HEAD_SHA=$(jq -r '.head.sha' pr.json)
-          HEAD_REF=$(jq -r '.head.ref' pr.json)
-          
-          echo "::set-output name=head_sha::$HEAD_SHA"
-          echo "::set-output name=head_ref::$HEAD_REF"
 
       - name: Create Check
         id: create_check
         run: |
           CHECK_RUN_ID=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
             -X POST https://api.github.com/repos/${{ github.repository }}/check-runs \
-            -d '{"name":"${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].check_name }}","head_sha":"${{ steps.get_pr.outputs.head_sha }}"}' \
+            -d '{"name":"${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].check_name }}","head_sha":"${{ needs.configure.outputs.head_sha }}"}' \
             | jq -r '.id') \
             && echo "::set-output name=check_run_id::$CHECK_RUN_ID"
 
@@ -118,5 +123,5 @@ jobs:
         run: |
           curl -s -H 'Authorization: token ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}' \
             https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].workflow_id }}/dispatches \
-            -d '{"ref":"${{ steps.get_pr.outputs.head_ref }}","inputs":{"check_run_id":"${{ steps.create_check.outputs.check_run_id }}"${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].workflow_inputs }}}}'
+            -d '{"ref":"${{ needs.configure.outputs.head_ref }}","inputs":{"check_run_id":"${{ steps.create_check.outputs.check_run_id }}"${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].workflow_inputs }}}}'
 
