Update ci-trigger-2.yml

diff --git a/.github/workflows/ci-trigger-2.yml b/.github/workflows/ci-trigger-2.yml
--- a/.github/workflows/ci-trigger-2.yml
+++ b/.github/workflows/ci-trigger-2.yml
@@ -114,8 +114,7 @@ jobs:
           http_code=$(curl -s -o check.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
             -X POST https://api.github.com/repos/${{ github.repository }}/check-runs \
             -d '{"name":"${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].check_name }}","head_sha":"${{ needs.configure.outputs.head_sha }}"}')
-          
-          echo $http_code
+      
           if [ "$http_code" != "201" ]; then
             echo "::error::Failed to create check"
             exit 1
@@ -128,6 +127,14 @@ jobs:
 
       - name: Trigger Workflow
         run: |
-          curl -s -H 'Authorization: token ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}' \
+          set -e
+          
+          http_code=$(curl -s -H 'Authorization: token ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}' \
             https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].workflow_id }}/dispatches \
-            -d '{"ref":"${{ needs.configure.outputs.head_ref }}","inputs":{"check_run_id":"${{ steps.create_check.outputs.check_run_id }}"${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].workflow_inputs }}}}'
+            -d '{"ref":"${{ needs.configure.outputs.head_ref }}","inputs":{"check_run_id":"${{ steps.create_check.outputs.check_run_id }}"${{ fromJSON(env.WORKFLOW_DATA)[matrix.workflow].workflow_inputs }}}}')
+          
+          echo $http_code
+          if [ "$http_code" != "201" ]; then
+            echo "::error::Failed to start workflow"
+            exit 1
+          fi
